language: php
dist: trusty
php:
  - '7.1'
  - '7.2'
  - '7.3'
before_script:
  - composer install
script:
  - php -v
  - phpunit --version
  - vendor/bin/codecept --version
  - vendor/bin/codecept run unit --coverage --coverage-xml
after_success:
#  - bash <(curl -s https://codecov.io/bash)
